# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
    tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build Web API Docker Image
        inputs:
          containerRegistry: 'PSBhatti Docker'
          repository: 'psbhatti/iotwebapi'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
          addBaseImageData: false

  - stage: Provision
    displayName: 'terraforming on Azure'
    dependsOn: Build
    jobs:
      - job: Provision
        displayName: 'Provisioning Azure resources'
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          - group: IoTVariables
        steps:
          - script: |
              set -e
  
              terraform init -input=false
              terraform apply -input=false -auto-approve
              terraform output -json > tf_outputs.json
              DB_SERVER=$(jq -r '.iot_sql_server_ip.value' tf_outputs.json)
              IOT_CONTAINER_NAME=$(jq -r '.iot_webapi_container.value' tf_outputs.json)
              echo "Extracted DB_SERVER value: $DB_SERVER"
              echo "Extracted container name value: $IOT_CONTAINER_NAME"
              echo "##vso[task.setvariable variable=DB_SERVER;]$DB_SERVER"
              echo "##vso[task.setvariable variable=IOT_CONTAINER_NAME;isOutput=true]$IOT_CONTAINER_NAME"
            name: 'RunTerraform'
            displayName: 'Run Terraform'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              TF_VAR_imagebuild: $(tag)
              TF_VAR_DB_PASSWORD: $(DB_PASSWORD)
              TF_VAR_DB_USER: $(DB_USER)
              TF_VAR_DB_NAME: $(DB_NAME)
          - script: |
              echo "Docker Containers After Provision:"
              docker ps -a
            displayName: 'Check Docker Containers'

  - stage: Migrate
    displayName: Apply EF Core Migrations
    dependsOn: Provision
    condition: succeeded()
    variables:
      IOT_CONTAINER_NAME: $[ dependencies.Provision.outputs['Provision.IOT_CONTAINER_NAME'] ]
    jobs:
    - job: Migrate
      displayName: Apply EF Core Migrations
      pool:
        vmImage: ubuntu-latest
      steps:
        - script: |
            echo "Installing dotnet-ef tool..."
            dotnet tool install --global dotnet-ef
            echo "Adding .NET tools to PATH..."
            echo "::add-path::$(Agent.ToolsDirectory)/dotnet/tools"
          displayName: 'Install dotnet-ef'
          
        - script: |
            echo "Setting environment to Production"
            export ASPNETCORE_ENVIRONMENT=Production
            echo "Current ASPNETCORE_ENVIRONMENT: $ASPNETCORE_ENVIRONMENT"
            echo "Container Name: $(IOT_CONTAINER_NAME)"
            docker ps -a
            echo "Applying EF Core Migrations..."
            docker exec -e ASPNETCORE_ENVIRONMENT=Production $(IOT_CONTAINER_NAME) dotnet ef database update --verbose
          displayName: 'Apply EF Core Migrations'