# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
    tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Docker@2
        displayName: Build Web API Docker Image
        inputs:
          containerRegistry: 'PSBhatti Docker'
          repository: 'psbhatti/iotwebapi'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(tag)
          addBaseImageData: false
  - stage: Provision
    displayName: 'terraforming on Azure'
    dependsOn: Build
    jobs:
      - job: Provision
        displayName: 'Provisioning Azure resources'
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          - group: IoTVariables
        steps:
          - script: |
              set -e
  
              terraform init -input=false
              terraform apply -input=false -auto-approve
              terraform output -json > tf_outputs.json
              DB_SERVER=$(jq -r '.iot_sql_server_ip.value' tf_outputs.json)
              echo "##vso[task.setvariable name=DB_SERVER;]$DB_SERVER"
            name: 'RunTerraform'
            displayName: 'Run Terraform'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              TF_VAR_imagebuild: $(tag)
              TF_VAR_DB_PASSWORD: $(DB_PASSWORD)
              TF_VAR_DB_USER: $(DB_USER)
              TF_VAR_DB_NAME: $(DB_NAME)
          - script: |
              echo "Installing dotnet-ef tool..."
              dotnet tool install --global dotnet-ef
              echo "Adding .NET tools to PATH..."
              echo "::add-path::$(Agent.ToolsDirectory)/dotnet/tools"
            displayName: 'Install dotnet-ef'
          - script: |
              echo "Env Variable values"
              echo "Db Password::" $(DB_PASSWORD)
              echo "sql server ip::" $(iot_sql_server_ip)
              echo "Db Serverp::" $(DB_SERVER)
              echo "Db User::" $(DB_User)
              echo "Db Name::" $(DB_Name)
          # Add EF Core migration step after provisioning
          - script: |
              echo "Setting environment to Production"
              export ASPNETCORE_ENVIRONMENT=Production
              echo "Applying EF Core Migrations..."
              dotnet ef database update --project $(Build.SourcesDirectory)/IoTWebApi.csproj --verbose
            displayName: 'Apply EF Core Migrations'
            env:
              DOTNET_CLI_HOME: $(Agent.TempDirectory)
              DB_PASSWORD: $(DB_PASSWORD)  # Ensure DB_PASSWORD is available
              DB_SERVER: $(DB_SERVER)  # Ensure DB_SERVER is fetched dynamically from Terraform output
              DB_USER: $(DB_User)
              DB_NAME: $(DB_Name)